server:
  port: 9103

spring:
  application:
    name: alerts-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    streams:
      application-id: ${KAFKA_STREAMS_APP_ID:alerts-service-app}
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.springframework.kafka.support.serializer.JsonSerde