apm-server:
  host: "0.0.0.0:8200"
  # Habilita ingesti√≥n OTLP (traces/metrics/logs) desde agentes OTel
  otlp:
    enabled: true

queue: {}

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  protocol: "http"
  username: "apm_writer"
  password: "changemeAPMWRITER"

logging:
  level: info
  selectors: ["*"]