server:
  port: 8080
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: kafka1:19092,kafka2:19093,kafka3:19094
  flyway:
    locations: classpath:db/migration,classpath:db/common
    baseline-on-migrate: true
    validate-on-migrate: false
app:
  jwt:
    secret: secret
    expiration: 86400