server:
  port: 8080
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: kafka:9092
    properties:
      reconnect.backoff.ms: 1000
      reconnect.backoff.max.ms: 30000
      retry.backoff.ms: 1000
      request.timeout.ms: 30000
      metadata.max.age.ms: 60000
    consumer:
      # Deserializadores tolerantes, con delegados String
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: true
    listener:
      missing-topics-fatal: false
    streams:
      # Aseguramos que Kafka Streams tenga application-id y bootstrap-servers
      application-id: ${KAFKA_STREAMS_APP_ID:eda-alerts-app}
      bootstrap-servers: kafka:9092
      properties:
        auto.offset.reset: earliest
        processing.guarantee: at_least_once
        reconnect.backoff.ms: 1000
        reconnect.backoff.max.ms: 30000
        retry.backoff.ms: 1000
        request.timeout.ms: 30000
        metadata.max.age.ms: 60000
  flyway:
    locations: classpath:db/migration,classpath:db/common
    baseline-on-migrate: true
    validate-on-migrate: false
app:
  jwt:
    secret: secret
    expiration: 86400